### ISSUE TITLE
Devboard + display

### ISSUE THREAD

**Issue by smutax** [ThomasH-W/ESP32-Radio-TTGO#1]
Hi there. Nice project. Would it be possible to use generic 30 pin esp32 dev board and attach compatible display to make up a required hardware for your project? Many thanks

**Comment by ThomasH-W** [comment]
Yes, you can attach another Display.
The easiest way is to use a Display based on ST7789V which is the one TTGO is using.
PINs
MOSI 19
SCLK 18
CS 5
DC 16
RST 23
BL 4

If you you a Display with another chip, you need to get yourself familiar with the display library and update the relevant items in there.

Thomas
