### ISSUE TITLE
error with HTTPClient

### ISSUE THREAD

**Issue by pierre04** [ThomasH-W/ESP32-Radio-TTGO#2]
Hello. I am trying to compile this project and I have some issues with HttpClient.

`$pio run`
 gives me an error : 
`src/wifiMgr.cpp:749:24: fatal error: HttpClient.h: No such file or directory`

So I installed lib #66 (HttpClient v.2.2.0)

Then, I have other errors :
`src/wifiMgr.cpp: In function 'void handleRadioConfig(AsyncWebServerRequest*)':
src/wifiMgr.cpp:442:49: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
         saveToSPIFFS(WIFI_SETUP_FILE, p->value());
                                                 ^
src/wifiMgr.cpp: In function 'void getCoverBMID(char*, char*)':
src/wifiMgr.cpp:757:5: error: 'HTTPClient' was not declared in this scope
     HTTPClient http;
     ^
src/wifiMgr.cpp:768:5: error: 'http' was not declared in this scope
     http.begin(buf);
     ^
src/wifiMgr.cpp: In function 'void getCoverJPG(char*)':
src/wifiMgr.cpp:796:5: error: 'HTTPClient' was not declared in this scope
     HTTPClient http;
     ^
src/wifiMgr.cpp:806:5: error: 'http' was not declared in this scope
     http.begin(buf);
     ^
` 
[error log.txt](https://github.com/ThomasH-W/ESP32-Radio-TTGO/files/7723282/error.log.txt)

I attach the full buid log

**Comment by Snapstromegon** [comment]
Hi,
thanks for reaching out. Sadly I'm not able to reproduce this on my machine (see the attached logs).

Looking at your logs and what you wrote it seems like the HttpClient.h library from the arduinoespressif32 framework can't be resolved. Can you please check that the framework is installed and setup for PlatformIO? Also maybe try runninng a clean all and then try building again.

@ThomasH-W and I  are developing on windows machines using the PlatformIO extension for VSCode, so I might not be able to support you with tooling issues specific to your platform (also could you please tell me some info like your OS and tooling you use?).

[log.txt](https://github.com/ThomasH-W/ESP32-Radio-TTGO/files/7723520/log.txt)

**Comment by Snapstromegon** [comment]
Hi @pierre04,
I think I found the issue (it was a casing issue with the HTTPClient.h lib).
Can you please try building the linked PR and report back?
It should solve your problem.

**Comment by pierre04** [comment]
Thank for this quick answer. It was the issue i think, since it compiles successfully now.
I do not have much time to further test, but I am confident.

By the way, I am using Platformio core cli version, with Debian Gnu/Linux
