### ISSUE TITLE
The radio is not working, no radio stations.

### ISSUE THREAD

**Issue by hevet** [ThomasH-W/ESP32-Radio-TTGO#4]
I compiled the code in Visual Studio, I uploaded the code to TTGO, I set the wifi network, I do not change the MQTT settings (I don't know what to set). Radio stations are defined in the setup.ini file. However, when started, it only shows "1" with a blue background. No station can be selected. You can switch to the clock with the buttons. What am I doing wrong? Does this have to do with the MQTT settings?

**Comment by Snapstromegon** [comment]
Hi, thanks for the feedback.
It seems like the code currently doesn't handle mqtt not being configured. I will bring this up with @ThomasH-W and we will probably created an update to the MQTT code (probably allowing to disable MQTT completely).

If that lands, we'll mention this issue in it, so you know when it is fixed.

**Comment by Snapstromegon** [comment]
After talking to @ThomasH-W this sounds like you didn't build and/or uploaded the filesystem to the ESP. MQTT should not be a problem here.

This is not described well right now in the README an will be updated. For now, please do the following steps and try again:

In the VSCode PlatformIO extension, run the "Build Filesystem Image" and "Upload Filesystem Image" tasks while the ESP is connected to the PC.
![image](https://user-images.githubusercontent.com/18480654/156924048-cb5f01c0-419e-45f5-8553-d0bcfc7412b1.png)

This needs to be done every time you change any file in the `/data` folder (like the setup.ini).

These steps build and upload the littlefs filesystem for the ESP, which holds the data.

**Comment by hevet** [comment]
Thank you very much for the answer, I will try to upload soon and let me know if it helped.

**Comment by hevet** [comment]
@Snapstromegon It works, thank you so much for the clarification. :)
