### ISSUE TITLE
Increase the station list.

### ISSUE THREAD

**Issue by hevet** [ThomasH-W/ESP32-Radio-TTGO#5]
There is a chance to increase the number of saved stations?

**Comment by Snapstromegon** [comment]
At the moment you can add up to 10 stations, but it should be possible to just increase the [setting in this line](https://github.com/ThomasH-W/ESP32-Radio-TTGO/blob/0a765c3a31ab96eaad73f1fb32df3b2eabfdd212/src/audio.cpp#L29). Just add more stations to your `data/setup.ini`.

**Comment by ThomasH-W** [comment]
If you need more than 10 stations, please update audio.cpp line 10
#define MAX_RADIO_STATIONS 10
SetupRadio setupRadio[MAX_RADIO_STATIONS];

**Comment by hevet** [comment]
@ThomasH-W it works :).

**Comment by ThomasH-W** [comment]
Thanks for letting us know. We will add this to the README
